import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './Skeleton.css';
export function Skeleton({ width = '100%', height = '20px', className = '' }) {
    return (_jsx("div", { className: `skeleton ${className}`, style: { width, height }, "aria-hidden": "true" }));
}
export function SkeletonCustomer() {
    return (_jsxs("div", { className: "skeleton-customer", children: [_jsxs("div", { className: "skeleton-row", children: [_jsx(Skeleton, { width: "60px", height: "16px" }), _jsx(Skeleton, { width: "150px", height: "16px" })] }), _jsxs("div", { className: "skeleton-row", children: [_jsx(Skeleton, { width: "60px", height: "16px" }), _jsx(Skeleton, { width: "200px", height: "16px" })] }), _jsxs("div", { className: "skeleton-row", children: [_jsx(Skeleton, { width: "60px", height: "16px" }), _jsx(Skeleton, { width: "80px", height: "16px" })] })] }));
}
export function SkeletonTransfer() {
    return (_jsxs("div", { className: "skeleton-transfer", children: [_jsxs("div", { className: "skeleton-header", children: [_jsx(Skeleton, { width: "80px", height: "20px" }), _jsx(Skeleton, { width: "70px", height: "24px" })] }), _jsx(Skeleton, { width: "140px", height: "14px" })] }));
}
export function SkeletonCorrelatedData() {
    return (_jsxs("div", { className: "skeleton-correlated-data", children: [_jsxs("div", { className: "skeleton-correlation-header", children: [_jsx(Skeleton, { width: "200px", height: "22px" }), _jsx(Skeleton, { width: "80px", height: "26px" })] }), _jsxs("div", { className: "skeleton-data-panels", children: [_jsxs("div", { className: "skeleton-data-panel", children: [_jsx(Skeleton, { width: "80px", height: "18px", className: "skeleton-panel-title" }), _jsxs("div", { className: "skeleton-panel-content", children: [_jsxs("div", { className: "skeleton-field", children: [_jsx(Skeleton, { width: "60px", height: "12px" }), _jsx(Skeleton, { width: "150px", height: "16px" })] }), _jsxs("div", { className: "skeleton-field", children: [_jsx(Skeleton, { width: "70px", height: "12px" }), _jsx(Skeleton, { width: "120px", height: "16px" })] }), _jsxs("div", { className: "skeleton-field", children: [_jsx(Skeleton, { width: "50px", height: "12px" }), _jsx(Skeleton, { width: "90px", height: "16px" })] })] })] }), _jsx("div", { className: "skeleton-connection", children: _jsx(Skeleton, { width: "40px", height: "20px" }) }), _jsxs("div", { className: "skeleton-data-panel", children: [_jsx(Skeleton, { width: "60px", height: "18px", className: "skeleton-panel-title" }), _jsxs("div", { className: "skeleton-panel-content", children: [_jsxs("div", { className: "skeleton-field", children: [_jsx(Skeleton, { width: "40px", height: "12px" }), _jsx(Skeleton, { width: "180px", height: "16px" })] }), _jsxs("div", { className: "skeleton-field", children: [_jsx(Skeleton, { width: "50px", height: "12px" }), _jsx(Skeleton, { width: "140px", height: "16px" })] }), _jsxs("div", { className: "skeleton-field", children: [_jsx(Skeleton, { width: "40px", height: "12px" }), _jsx(Skeleton, { width: "70px", height: "16px" })] })] })] })] }), _jsxs("div", { className: "skeleton-quick-actions", children: [_jsx(Skeleton, { width: "120px", height: "18px", className: "skeleton-actions-title" }), _jsxs("div", { className: "skeleton-actions-grid", children: [_jsx(Skeleton, { width: "100px", height: "36px" }), _jsx(Skeleton, { width: "120px", height: "36px" }), _jsx(Skeleton, { width: "90px", height: "36px" }), _jsx(Skeleton, { width: "110px", height: "36px" })] })] })] }));
}
